site_name: Übung Elektronische Musik
extra_css:
  - style.css
site_url: https://teymuri.github.io/musikelektronik/
nav:
  - Modulbeschreibung: index.md
  - Kontakt: kontakt.md
  - Übersicht: 
    - Wintersemester:
      - Sprache: lang.md
      - Die ersten Töne: first_sounds.md
  - Literatur: lit.md
