site_name: Modul Musik-Elektronik
site_url: https://teymuri.github.io/musikelektronik/
nav:
  - Modulbeschreibung: index.md
  - Kontakt: kontakt.md
  - Kapitel: 
    - Namen: namen.md
    - Datenstrukturen: daten.md
